package com.forgebuild.engine.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Material Symbols icon set bundled locally (offline-friendly, no runtime font).
 * Icon glyphs are generated by tools/gen_icons.py which converts Material
 * Symbols SVG path data into Compose ImageVectors in EngineIconsGenerated.kt.
 */
object EngineIcons {
    val Bolt: ImageVector get() = EngineIconsGenerated.Bolt
    val Settings: ImageVector get() = EngineIconsGenerated.Settings
    val Add: ImageVector get() = EngineIconsGenerated.Add
    val Home: ImageVector get() = EngineIconsGenerated.Home
    val Search: ImageVector get() = EngineIconsGenerated.Search
    val ArrowBack: ImageVector get() = EngineIconsGenerated.ArrowBack
    val Apps: ImageVector get() = EngineIconsGenerated.Apps
    val Refresh: ImageVector get() = EngineIconsGenerated.Refresh
    val PlayArrow: ImageVector get() = EngineIconsGenerated.PlayArrow
    val Download: ImageVector get() = EngineIconsGenerated.Download
    val ContentCopy: ImageVector get() = EngineIconsGenerated.ContentCopy
    val CheckCircle: ImageVector get() = EngineIconsGenerated.CheckCircle
    val Schedule: ImageVector get() = EngineIconsGenerated.Schedule
    val OpenInNew: ImageVector get() = EngineIconsGenerated.OpenInNew
    val Code: ImageVector get() = EngineIconsGenerated.Code
    val History: ImageVector get() = EngineIconsGenerated.History
    val Lock: ImageVector get() = EngineIconsGenerated.Lock
    val Build: ImageVector get() = EngineIconsGenerated.Build
}
