#!/usr/bin/env python3
"""
ForgeBuild icon bundler: converts Material Symbols SVG path data into a Kotlin
file of Compose ImageVectors (EngineIconsGenerated.kt), so apps bundle only the
icons they use — lean and fully offline.

Usage:
  python3 tools/gen_icons.py add search home "settings:Settings" bolt:Bolt arrow_back:ArrowBack

Each arg is `<material_symbol_name>[:KotlinPropertyName]`. SVG path data is read
from tools/icons/*.svg (download the symbol's SVG from fonts.google.com/icons,
"Material Symbols", SVG download), or passed inline as name:Prop=pathData.

Output: app/src/main/java/com/forgebuild/engine/ui/icons/EngineIconsGenerated.kt
After adding icons, register getters in EngineIcons.kt.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / "tools" / "icons"
OUT = ROOT / "app/src/main/java/com/forgebuild/engine/ui/icons/EngineIconsGenerated.kt"

HEADER = """// GENERATED by tools/gen_icons.py — do not edit by hand.
package com.forgebuild.engine.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

internal object EngineIconsGenerated {
"""

def prop_name(sym: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[_\-\s]+", sym))

def load_path(sym: str, inline: str | None) -> str:
    if inline: return inline
    f = ICONS_DIR / f"{sym}.svg"
    if not f.exists():
        sys.exit(f"missing {f}: download the Material Symbols SVG for '{sym}' (or pass inline path data)")
    m = re.search(r'd="([^"]+)"', f.read_text())
    if not m: sys.exit(f"no path data in {f}")
    return m.group(1)

def main():
    entries = []
    for arg in sys.argv[1:]:
        inline = None
        if "=" in arg: arg, inline = arg.split("=", 1)
        if ":" in arg: sym, prop = arg.split(":", 1)
        else: sym, prop = arg, prop_name(arg)
        entries.append((prop, load_path(sym, inline)))
    body = HEADER
    for prop, d in entries:
        body += f'''
    val {prop}: ImageVector by lazy {{
        ImageVector.Builder(name = "{prop}", defaultWidth = 24.dp, defaultHeight = 24.dp,
            viewportWidth = 24f, viewportHeight = 24f)
            .path(fill = SolidColor(Color.Black)) {{ pathData = parsePathData() }}
            .build()
    }}
    private val {prop}_data = "{d}"
'''
    # simpler: emit path with addPathNodes
    body = HEADER
    for prop, d in entries:
        body += f'''
    val {prop}: ImageVector by lazy {{
        ImageVector.Builder(name = "{prop}", defaultWidth = 24.dp, defaultHeight = 24.dp,
            viewportWidth = 24f, viewportHeight = 24f)
            .path(fill = SolidColor(Color.Black), pathData = androidx.compose.ui.graphics.vector.PathParser().parsePathString("{d}").toNodes())
            .build()
    }}
'''
    body += "}\n"
    OUT.write_text(body)
    print(f"wrote {OUT} with {len(entries)} icons:", ", ".join(p for p, _ in entries))

if __name__ == "__main__":
    main()
