package com.forgebuild.engine.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Material Symbols icon set bundled locally (offline-friendly, no runtime font).
 * Icon glyphs are generated by tools/gen_icons.py which converts Material
 * Symbols SVG path data into Compose ImageVectors in EngineIconsGenerated.kt.
 * Generated apps: NEVER use emoji or mismatched icon sets for iconography —
 * extend this set via tools/gen_icons.py instead.
 */
object EngineIcons {
    val Bolt: ImageVector get() = EngineIconsGenerated.Bolt
    val Settings: ImageVector get() = EngineIconsGenerated.Settings
    val Add: ImageVector get() = EngineIconsGenerated.Add
    val Home: ImageVector get() = EngineIconsGenerated.Home
    val Search: ImageVector get() = EngineIconsGenerated.Search
    val PlayArrow: ImageVector get() = EngineIconsGenerated.PlayArrow
    val Movie: ImageVector get() = EngineIconsGenerated.Movie
    val Refresh: ImageVector get() = EngineIconsGenerated.Refresh
    val CheckCircle: ImageVector get() = EngineIconsGenerated.CheckCircle
    val Error: ImageVector get() = EngineIconsGenerated.Error
    val Link: ImageVector get() = EngineIconsGenerated.Link
    val ContentCut: ImageVector get() = EngineIconsGenerated.ContentCut
    val Logout: ImageVector get() = EngineIconsGenerated.Logout
    val VideoLibrary: ImageVector get() = EngineIconsGenerated.VideoLibrary
    val Tasks: ImageVector get() = EngineIconsGenerated.Tasks
    val Send: ImageVector get() = EngineIconsGenerated.Send
    val ArrowBack: ImageVector get() = EngineIconsGenerated.ArrowBack
}
