package com.forgebuild.engine.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Material Symbols icon set bundled locally (offline-friendly, no runtime font).
 * Icon glyphs are generated by tools/gen_icons.py which converts Material
 * Symbols SVG path data into Compose ImageVectors in EngineIconsGenerated.kt.
 * Generated apps: NEVER use emoji or mismatched icon sets for iconography —
 * extend this set via tools/gen_icons.py instead.
 */
object EngineIcons {
    val Bolt: ImageVector get() = EngineIconsGenerated.Bolt
    val Settings: ImageVector get() = EngineIconsGenerated.Settings
    val Add: ImageVector get() = EngineIconsGenerated.Add
    val Home: ImageVector get() = EngineIconsGenerated.Home
    val Search: ImageVector get() = EngineIconsGenerated.Search
    val ArrowBack: ImageVector get() = EngineIconsGenerated.ArrowBack
}
